/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWhatifRouteImport } from './routes/dashboard.whatif'
import { Route as DashboardSopDemoRouteImport } from './routes/dashboard.sop-demo'
import { Route as DashboardSolverRouteImport } from './routes/dashboard.solver'
import { Route as DashboardSkusRouteImport } from './routes/dashboard.skus'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPosRouteImport } from './routes/dashboard.pos'
import { Route as DashboardForecastingRouteImport } from './routes/dashboard.forecasting'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatifRoute = DashboardWhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSopDemoRoute = DashboardSopDemoRouteImport.update({
  id: '/sop-demo',
  path: '/sop-demo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolverRoute = DashboardSolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkusRoute = DashboardSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPosRoute = DashboardPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastingRoute = DashboardForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skus': typeof DashboardSkusRoute
  '/dashboard/solver': typeof DashboardSolverRoute
  '/dashboard/sop-demo': typeof DashboardSopDemoRoute
  '/dashboard/whatif': typeof DashboardWhatifRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skus': typeof DashboardSkusRoute
  '/dashboard/solver': typeof DashboardSolverRoute
  '/dashboard/sop-demo': typeof DashboardSopDemoRoute
  '/dashboard/whatif': typeof DashboardWhatifRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skus': typeof DashboardSkusRoute
  '/dashboard/solver': typeof DashboardSolverRoute
  '/dashboard/sop-demo': typeof DashboardSopDemoRoute
  '/dashboard/whatif': typeof DashboardWhatifRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/forecasting'
    | '/dashboard/pos'
    | '/dashboard/settings'
    | '/dashboard/skus'
    | '/dashboard/solver'
    | '/dashboard/sop-demo'
    | '/dashboard/whatif'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/forecasting'
    | '/dashboard/pos'
    | '/dashboard/settings'
    | '/dashboard/skus'
    | '/dashboard/solver'
    | '/dashboard/sop-demo'
    | '/dashboard/whatif'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/forecasting'
    | '/dashboard/pos'
    | '/dashboard/settings'
    | '/dashboard/skus'
    | '/dashboard/solver'
    | '/dashboard/sop-demo'
    | '/dashboard/whatif'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatif': {
      id: '/dashboard/whatif'
      path: '/whatif'
      fullPath: '/dashboard/whatif'
      preLoaderRoute: typeof DashboardWhatifRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sop-demo': {
      id: '/dashboard/sop-demo'
      path: '/sop-demo'
      fullPath: '/dashboard/sop-demo'
      preLoaderRoute: typeof DashboardSopDemoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solver': {
      id: '/dashboard/solver'
      path: '/solver'
      fullPath: '/dashboard/solver'
      preLoaderRoute: typeof DashboardSolverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skus': {
      id: '/dashboard/skus'
      path: '/skus'
      fullPath: '/dashboard/skus'
      preLoaderRoute: typeof DashboardSkusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pos': {
      id: '/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardPosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecasting': {
      id: '/dashboard/forecasting'
      path: '/forecasting'
      fullPath: '/dashboard/forecasting'
      preLoaderRoute: typeof DashboardForecastingRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardForecastingRoute: typeof DashboardForecastingRoute
  DashboardPosRoute: typeof DashboardPosRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkusRoute: typeof DashboardSkusRoute
  DashboardSolverRoute: typeof DashboardSolverRoute
  DashboardSopDemoRoute: typeof DashboardSopDemoRoute
  DashboardWhatifRoute: typeof DashboardWhatifRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardForecastingRoute: DashboardForecastingRoute,
  DashboardPosRoute: DashboardPosRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkusRoute: DashboardSkusRoute,
  DashboardSolverRoute: DashboardSolverRoute,
  DashboardSopDemoRoute: DashboardSopDemoRoute,
  DashboardWhatifRoute: DashboardWhatifRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
